### ISSUE TITLE
Background colour?

### ISSUE THREAD

**Issue by mato0039** [mato0039/arrrgenes-treasure-tours#1]
Hi Christina

Markbot says the contrast between the h2 and the banner image isn't enough? I'm not sure how to fix this. I tried to make the h2 bold but that doesn't change anything. 

Would you able to help? 

Cathy

@muxlowc

<img width="518" alt="Screen Shot 2020-03-27 at 9 17 38 AM" src="https://user-images.githubusercontent.com/55108737/77760001-0f7d2680-700c-11ea-85f1-4425741443d3.png">

**Comment by muxlowc** [comment]
@mato0039 so you need to add in 2 more colours it looks like:

In css:
1) to your .btn-banner: hover & focus, add   outline-color: #fff;
2) to your .banner add background-color: #704c2a;

That should help!

**Comment by mato0039** [comment]
Thank you Christina! xo
Cathy
